# Generated by Django 4.2.3 on 2023-08-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0002_advertisement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Advertisement',
        ),
        migrations.AlterField(
            model_name='onlineshop',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='id'),
        ),
        migrations.AlterModelTable(
            name='onlineshop',
            table='advertisements',
        ),
    ]
