# Generated by Django 4.2.3 on 2023-08-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0003_delete_advertisement_alter_onlineshop_id_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='online_shop',
        ),
    ]
