# Generated by Django 4.2.3 on 2023-08-13 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0004_alter_onlineshop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='app_online_shop_onlineshop',
        ),
    ]
