# Generated by Django 4.2.3 on 2023-08-13 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_online_shop', '0005_alter_onlineshop_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onlineshop',
            table='online_shop',
        ),
    ]
